Draft: Add tutorial for LAMP role
flyingcircusio/doc pull request #18
Opened 2022-03-29 06:21 UTC by zagy

Also remove the ancient django/gentoo tutorial which does more harm than good.

- [ ] Fix links to nixos platform. @dpausp how does that work?

2022-05-03 04:45 UTC, zagy commented on src/guide/deployment/lamp.rst
> +Enable a MySQL role of your choice, e.g. mysql57, percona80, in the VM dashboard on https://my.flyingcircus.io/. See :ref:`nixos-mysql` for details.
@dpausp how to I link to the *current* nixos version here?

2022-05-12 13:10 UTC, ctheune requested changes

2022-05-12 13:10 UTC, ctheune commented on src/guide/deployment/index.rst
>  section contains a walk-through of a Django installation.
I think this isn't true any longer ... ;)

2022-05-12 13:10 UTC, ctheune commented on src/guide/deployment/lamp.rst
> +Context: fc platform, user management, multi vm?
?

2022-05-12 13:10 UTC, ctheune commented on src/guide/deployment/lamp.rst
> +What you should know before:
... "before starting:"

2022-05-12 13:10 UTC, ctheune commented on src/guide/deployment/lamp.rst
> +* NGINX: SSL termination
and domain/vhost-specific configs

2022-05-12 13:10 UTC, ctheune commented on src/guide/deployment/lamp.rst
> +If you just enabled a MySQL role it might now be available on the VM, yet. Call ``sudo fc-manage -eb`` to force a build. The ``-e`` option is there to reload the configuration you have set in the VM
it might "not" be

2022-05-12 13:10 UTC, ctheune commented on src/guide/deployment/lamp.rst
> +If you just enabled a MySQL role it might now be available on the VM, yet. Call ``sudo fc-manage -eb`` to force a build. The ``-e`` option is there to reload the configuration you have set in the VM
"so it's usually omitted when applying local changes "

2022-05-12 13:10 UTC, ctheune commented on src/guide/deployment/lamp.rst
> +To create a service specific MySQL user and database you switch to the mysql user and start a mysql shell:
service-specific

2022-05-12 13:10 UTC, ctheune commented on src/guide/deployment/lamp.rst
> +You will of course need username and password for your application. We will not go into detail here.
a real username and password for your application

2022-05-12 13:10 UTC, ctheune commented on src/guide/deployment/lamp.rst
> +You will of course need username and password for your application. We will not go into detail here.
"We will not go into detail here." -> let's just drop this superfluous sentence

2022-05-12 13:10 UTC, ctheune commented on src/guide/deployment/lamp.rst
> +          MaxRequestWorkers 5
I'd leave this one out in the tutorial. Otherwise people start always copying this, overriding the quite sensible default.

2022-05-12 13:10 UTC, ctheune commented on src/guide/deployment/lamp.rst
> +
One thing  that would be interesting to show is that you can

a) put all this config into a single file and 
b) use variables to e.g. consistently refer to the virtual host port (8000)

2022-06-28 07:00 UTC, merged