Update structure to fit BDSG
flyingcircusio/doc pull request #52
Opened 2024-11-11 10:35 UTC by zagy

ISMS-147656

@ctheune please review english document. I mostly moved text around but there are also some new parts.

- [x] Update english text
- [x] Review englisch text
- [x] Update translation
- [x] Review translation

2024-12-03 09:00 UTC, ctheune commented
The english version is fine to me, now. I adjusted a few language things and made a note about S3 storage separation

2025-02-26 07:34 UTC, ctheune commented on src/locales/de/LC_MESSAGES/reference/security/data-protection.po
Da gibt es einige Strings die nicht greifen, z.b. die drei Items in der Aufzählung neben dem Zertifizierungslogo.

2025-02-26 07:38 UTC, ctheune requested changes
Also bei mir im rendering ist da ca jeder zweite bis dritte Satz nicht übersetzt, das kann ich leider nicht vernünftig reviewen ...

2025-02-28 06:20 UTC, zagy commented
> Also bei mir im rendering ist da ca jeder zweite bis dritte Satz nicht übersetzt, das kann ich leider nicht vernünftig reviewen ...

Hm … also bei mir tut das … `make html-de`

2025-05-16 09:58 UTC, ctheune commented
Dinge, die in der deutschen Übersetzung des Datenschutz-Dokuments grad aufgefallen sind, aber im Diff nicht einfach markierbar:

* [ ] link zum BDSG ist nicht richtig gerendert
* [ ] `two-factor security for granting access with logging`
* [ ] `[cryptsetup] (https://gitlab.com/cryptsetup/cryptsetup)`
* [ ] `User identification must be performed using personal credentials`
* [ ] "werden überwacht müssen dokumentiert werden"
* [ ] "Privilegierter administrativer Zugriff wird generell nicht an Kunden gewährt. In Fällen, in denen eine andere Person, die kein Administrator ist, benötigt wird, um ein Problem zu lösen, muss eine gemeinsame Sitzung zwischen einem Administrator und der anderen Person eingerichtet werden (z.B. mit screen)." → das ist inhaltlich so nicht mehr korrekt, zum einen machen wir das durchaus und zum anderen → ubuntu vms
* [ ] "Flying Circus unterhält eine Reihe von Berechtigungen" das ist komisches wording ...  was tun wir womit? Soll das heißen, dass es unterschiedliche permissions gibt?
* [ ] "dass Administratoren auf einem niedrigen technischen Niveau Datensätze eingeben" soll bestimmt "low level" heißen ... 
* [ ] `(8) Transport control`
* [ ] "Der Speicherverkehr" ... hmnjn.
* [ ] "Maschinen, auf denen Kunden administrative Privilegien gewährt werden, dürfen sich nicht direkt mit dem Speichernetzwerk verbinden" das ist anders umgesetzt und ist tatsächlich grad auch eine potentielle Schwachstelle, z.b. mit den devhosts. da sollten wir nochmal drüber reden
* [ ] Backups werden entweder über einen verschlüsselten ... das ist irgendwie doppelt gemoppelt
* [ ] " Log-Daten können auch über einen verschlüsselten Kanal an einen von Flying Circus betriebenen Log-Server am selben Standort übertragen werden. " ist das inhaltlich korrekt? ich glaube nicht dass wir da verschlüsseln
* [ ] `(9) Recovery`
* [ ] "Dies kann aufgrund von breit angelegten Wartungsverträgen oder aufgrund von spezifischen Supportanfragen sein." da fehlt noch was um das Hilfsverb zu ergänzen.
* [ ] "The availability of resources depending on the..."
* [ ] "Die Auswahl der Hardware wird vom Flying Circus mit professionellem Equipment und Anbietern durchgeführt." ... hmpf. übersetzungsautomat.
* [ ] "Der Flying Circus ermöglicht Standardverfahren zur Erhöhung der Verfügbarkeit" ... blah
* [ ] "Desaster" vs. "Disaster". Wir haben da vermischte Sprachregelungen, da greift der Automat immer wieder daneben.
* [ ] "Maschinen führen Infrastrukturaufgaben aus. So müssen sie Daten verarbeiten, die zu mehreren Kunden gehören." sprache
* [ ] "Projekte teilen sich dasselbe Set an Benutzerkonten und Berechtigungen" ... projekte vs. ressourcengruppen und "set".
* [ ] "Der Zugriff auf S3-kompatible Objektspeicher-Buckets"
* [ ] "Fußzeile"

2025-05-16 11:52 UTC, merged